"""empty message

Revision ID: fe4a23c79994
Revises: e9da4f9c2397
Create Date: 2017-01-05 16:38:59.963911

"""

# revision identifiers, used by Alembic.
revision = 'fe4a23c79994'
down_revision = 'e9da4f9c2397'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rec',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('rec_movie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.movie_id'], ),
    sa.ForeignKeyConstraint(['rec_movie_id'], ['movies.movie_id'], ),
    sa.PrimaryKeyConstraint('movie_id', 'rec_movie_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rec')
    # ### end Alembic commands ###
